name: cpsumotorpooldriverapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.0-296.3.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  
  assets:
    - assets/image/cpsu logo.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/fonts.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
          style: italic
